TourType.create(name: "Crater Lake")
TourType.create(name: "Multnomah Falls")
TourType.create(name: "Cannon Beach")
TourType.create(name: "Bend")
TourType.create(name: "Mount Hood")

Amenity.create(name: "Pool")
Amenity.create(name: "Rec Room")
Amenity.create(name: "Movie Theater")
Amenity.create(name: "On Site Doctor")
Amenity.create(name: "Time Machine")
